#!/bin/sh

#
# Prettier
#
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed "s| |\\ |g")
if [[ "$STAGED_FILES" = "" ]]; then
  printf "\n\033[0;32mNo files to run through Prettier.\033[0m\n"
else
  printf "\n\033[0;32mRunning Prettier...\033[0m Fix any errors with 'npx prettier --write $STAGED_FILES'.\n"|tr "\n" " "

  # Check prettier but do not change
  echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --check

  # Write prettier and commit changes
  #echo "$ALL_STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
  #echo "$ALL_STAGED_FILES" | xargs git add
fi

#
# ESLint
#
STAGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")

if [[ "$STAGED_JS_FILES" = "" ]]; then
  printf "\n\033[0;32mNo JS files for ESLint\033[0m\n"
else
  printf "\n\033[0;32mRunning ESLint...\033[0m Rerun/attempt to fix any errors with 'npx eslint --fix $STAGED_JS_FILES'\n"|tr "\n" " "
  echo "$STAGED_JS_FILES" | xargs ./node_modules/.bin/eslint
fi

exit 0
